export const START_NEW_TOURNAMENT = 'START_NEW_TOURNAMENT';
export const SET_ACTIVE_TOURNAMENT = 'SET_ACTIVE_TOURNAMENT';
export const UNSET_ACTIVE_TOURNAMENT = 'UNSET_ACTIVE_TOURNAMENT';
export const DELETE_TOURNAMENT = 'DELETE_TOURNAMENT';
